// using GoCartaDLL;
using Microsoft.Win32;
using System;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Text;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Security.Cryptography;
using System.Windows.Forms;
using System.Xml.Linq;
using static System.Windows.Forms.VisualStyles.VisualStyleElement.Tab;

namespace GoPlanner
{
  public partial class GoPlanner : Form
  {
    public readonly int bSide = 19;
    public AStone[,] thePoints;
    public short capturedBlacks = 0;
    public short capturedWhites = 0;
    private Pen myPen;
    // colors at https://learn.microsoft.com/en-us/dotnet/api/system.windows.media.brushes?view=windowsdesktop-8.0
    private Brush brushWhite = Brushes.White;
    private Brush brushBlack = Brushes.Black;
    private Brush brushDarkWhite = Brushes.LightGray;
    private Brush brushLightBlack = Brushes.Gray;
    private Brush brushRed = Brushes.Red;


    private bool mouseDragging = false;    // dragging mouse to form selection rectangle
    private bool mouseDown = false;
    private int mouseDownX;
    private int mouseDownY;
    // dragging contents of selection rectangle = move, indicated by cursor = hand
    private long mouseFirstDownMs;
    private bool ignoreNextMouseUp = false;
    private int mouseBoardX = -1;
    private int mouseBoardY = -1;
    private System.Timers.Timer mouseMoveTimer;

    private readonly Selection selection;
    public readonly StatusM statusM;

    private ToolsOptions toolsOptions;

    public string programTitle;
    public string programVersion;
    public string programBuildDate;

    private Cursor whiteCursor;
    private Cursor blackCursor;

    private string TSTextBox1Text;

    public GoPlanner()
    {
      InitializeComponent();
      InitCutCopyPaste();
      InitUndoRedo();
      InitFiles();
      InitPlayReplay();
      InitScoreControl();
      prSLider.Invalidate();

      // could adjust registry here so that FriendlyAppName is programTitle....
      // location of .exe file in assembly.Location, see HelpAbout.cs
      GetSetNames();
      FormClosing += GoPlanner_FormClosing;
 
      thePoints = CreateStones(bSide, bSide);

      myPen = new Pen(Brushes.White, 1);
      panelMain.BackColor = Color.Wheat;
      panelMain.Resize += PanelMain_Resize;
      panelMain.MouseMove += PanelMain_MouseMove;
      panelMain.MouseUp += PanelMain_MouseUp;
      panelMain.MouseDown += PanelMain_MouseDown;
      panelMain.KeyPress += PanelMain_KeyPress;
      panelMain.KeyDown += PanelMain_KeyDown;
      toolsOptions = new ToolsOptions(this);

      statusM = new StatusM(TSTextBox2);
      statusM.Set("Click somewhere or File / Open");
      CalcTSTextBox2Width();
      blackCursor = SetCustomCursor("cursor-black");
      whiteCursor = SetCustomCursor("cursor-white");

      LoadSettings();
      toolsOptions.InitLabels();

      EnableCutCopy(false);
      selection = new Selection(this);

      mouseMoveTimer = new System.Timers.Timer(500);
      mouseMoveTimer.Elapsed += PanelMain_MyHover;
      mouseMoveTimer.AutoReset = false;
      mouseMoveTimer.Enabled = false;
#if !DEBUG
      TestToolStripMenuItem.Visible = false;
#endif
    }

    private void GetSetNames()
    {
      // AssemblyTitleAttribute and AssemblyFileVersionAttribute come from AssemblyInfo.cs
      // AssemblyInfo.cs provides info for file properties
      Assembly assembly = Assembly.GetExecutingAssembly();
      AssemblyTitleAttribute assemblyTitle = assembly.GetCustomAttribute<AssemblyTitleAttribute>();
      AssemblyFileVersionAttribute fileVersion = assembly.GetCustomAttribute<AssemblyFileVersionAttribute>();
      string keyName = "HKEY_CLASSES_ROOT\\Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache\\";
      string valueName = assembly.Location + ".FriendlyAppName";
      // assembly.Location = path of .exe file
      // in debug that's C:\Users\georg\My Drive\repos\Go\Go\bin\Debug\Go.exe.FriendlyAppName

      // build date is in format dd/mm/yyyy, generated by pre-build event into resources BuildDate.txt
      // see Go (project) right-click / Properties / Build Events and Resources tabs
      string day = Properties.Resources.BuildDate.Substring(0, 2);
      string month = Properties.Resources.BuildDate.Substring(3, 2);
      string year = Properties.Resources.BuildDate.Substring(6, 4);
      DateTime buildDate = new DateTime(int.Parse(year), int.Parse(month), int.Parse(day), 0,0,0,0);

      programTitle = assemblyTitle.Title;
      Text = programTitle;      // title bar of main form    
      programVersion = fileVersion.Version;
      programBuildDate = buildDate.ToLongDateString();

      // now get programTitle into registry entry for this instance (if not already there)
      // see https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.registry?view=net-9.0 
      try
      {
        bool updateNeeded = false;
        object testValue = Registry.GetValue(keyName, valueName, "");
        if (testValue == null) 
        {  
          updateNeeded = true;
        }
        else
        {
          if (testValue.GetType().Name != "String")
          {
            updateNeeded = true;
          }
          else 
          {
            if ((string)testValue != programTitle)
            {
              updateNeeded = true;
            }
          }
        }
        if (updateNeeded)
        {
          Registry.SetValue(keyName, valueName, programTitle);
        }
      }
      catch (Exception ex) 
      {
        new MyMessageBox(ex.Message, "Registry Error", this);
      }
    }

    private Cursor SetCustomCursor(string fileName)
    {
      // Load the custom cursor image from the embedded resources
      // it must have properties / Build Action: Embedded Resource
      Assembly assembly = Assembly.GetExecutingAssembly();
      using (Stream stream = assembly.GetManifestResourceStream("GoPlanner.img." + fileName +".png"))
      {
        if (stream != null)
        {
          Bitmap cursorBitmap = new Bitmap(stream);
          IntPtr cursorPtr = cursorBitmap.GetHicon();
          return new Cursor(cursorPtr);
        }
      }
      return null;
    }
    private void GoPlanner_FormClosing(object sender, FormClosingEventArgs e)
    {
      // could check for file saved here
      SaveSettings();
    }
    protected override void SetVisibleCore(bool value)
    // under Copilot advice, to avoid showing initial wrong window location
    {
      if (!IsHandleCreated)
      {
        CreateHandle();
        // Set window location before it becomes visible
        if (Properties.Settings.Default.WindowLocation != Point.Empty)
        {
          Location = Properties.Settings.Default.WindowLocation;
        }
      }
      base.SetVisibleCore(value);
    }
    private void LoadSettings()
    {
      // Load window location
      if (Properties.Settings.Default.WindowLocation != Point.Empty)
      {
        Location = Properties.Settings.Default.WindowLocation;
      }
      if (Properties.Settings.Default.WindowSize != Size.Empty)
      {
        Size = Properties.Settings.Default.WindowSize;
      }
      if (Properties.Settings.Default.WindowState == 1)
      {
        WindowState = FormWindowState.Normal;
      }
      if (Properties.Settings.Default.WindowState == 2)
      {
        WindowState = FormWindowState.Maximized;
      }
      toolsOptions.LoadOptions();
    }

    private void SaveSettings()
    {
      Properties.Settings.Default.WindowLocation = Location;

      if (WindowState == FormWindowState.Normal)
      {
        Properties.Settings.Default.WindowState = 1;
        Properties.Settings.Default.WindowSize = Size;
      }
      if (WindowState == FormWindowState.Maximized)
      {
        Properties.Settings.Default.WindowState = 2;
      }

      toolsOptions.SaveOptions();

      Properties.Settings.Default.Save();
    }

    private void PanelMain_Resize(object sender, EventArgs e)
    {
      panelMain.Invalidate();
      CalcPrSliderlWidth();
      prSLider.Invalidate();
      CalcTSTextBox2Width();
    }
    private void CalcTSTextBox2Width()
    {
      if (!gameInProgress)
      {
        TSTextBox2.Width = toolStrip2.Width - TSTextBox1.Width - 50;
        YouName.Visible = false;
        YouMainTime.Visible = false;
        YouColor.Visible = false;
        OpponentName.Visible = false;
        OpponentMainTime.Visible = false;
        OpponentColor.Visible = false;
      }
      else
      {
        YouName.Visible = true;
        YouMainTime.Visible = true;
        YouColor.Visible = true;
        OpponentName.Visible = true;
        OpponentMainTime.Visible = true;
        OpponentColor.Visible = true;
        TSTextBox2.Width = toolStrip2.Width - TSTextBox1.Width - 50 -
          YouName.Width - YouMainTime.Width - YouColor.Width -
          OpponentName.Width - OpponentMainTime.Width - OpponentColor.Width;
      }
    }
    private void PanelMain_KeyPress(object sender, KeyPressEventArgs e)
    {
      if (gameInProgress) return;
      // Key press only works if PanelMain has focus
      // https://stackoverflow.com/questions/2132130/how-to-get-keypress-event-in-windows-panel-control-in-c-sharp
      switch (e.KeyChar)
      {
        case (char)27:    // escape
          ignoreNextMouseUp = true;
          selection.Cancel();
          if ((panelMain.Cursor == Cursors.Cross) || (panelMain.Cursor == Cursors.Hand))
          {
            CancelPaste();
          }
          break;
        case 'b':
        case 'B':
          TSBblack_Click(null, null);
          break;
        case 'w':
        case 'W':
          TSBwhite_Click(null, null);
          break;
      }
    }
    private void PanelMain_KeyDown(object sender, KeyEventArgs e)
    {
      if (gameInProgress) return;
      switch (e.KeyCode)
      {
        case Keys.Left:
          UndoToolStripMenuItem_Click(null, null);
          return;
        case Keys.Right:
          RedoToolStripMenuItem_Click(null, null);
          return;
      }
    }

    // MouseClick always precedes MouseUp with same coordinates
    // MouseDown precedes both, possibly different coordinates.
    // So we do not use MouseClick. It would be confusing
    // see FormCutCopyPaste.cs for more details (possibly)
    private void PanelMain_MouseUp(object sender, MouseEventArgs e)
    {
      if (ignoreNextMouseUp)
      {
        mouseDown = false;
        mouseDragging = false;
        ignoreNextMouseUp = false;
        return;
      }
      int boardX = BoardXYfromPixelXY(e.X);
      int boardY = BoardXYfromPixelXY(e.Y);
      panelMain.Focus();
      mouseDown = false;
      if (panelMain.Cursor == Cursors.Cross)
      {
        EndPaste(e);
        statusM.Clear();
        return;
      }
      if (panelMain.Cursor == Cursors.Hand)
      {
        // we were moving. If one stone and not moved and was quick, not much of a drag. 
        // in that case we want to treat like click
        bool properMove = true;
        long mouseWasDownMs = (DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond) - mouseFirstDownMs;
        if ((selection.movePoints.GetLength(0) * selection.movePoints.GetLength(1) == 1) &&
          boardX == selection.TLx() && boardY == selection.TLy() &&
          mouseWasDownMs < 200)
        {
          properMove = false;
        }
        EndMove(e);
        if (properMove)
        {
          statusM.Clear();
          return;
        }
        UnSaveState("Mouse up");      // Commence move had a SaveState, which we dont need
      }
      mouseDown = false;
      if (!mouseDragging)
      {
        if (!selection.Cancel())
        {
          if (NearPoint(e.X, e.Y))
          {
            if (gameInProgress)
            {
              MouseUpInGame(boardX, boardY);
              return;
            }
            string statusMess = "";
            SaveState("Mouse Up");
            if (thePoints[boardX, boardY].color == 0)
            {
              byte colorAdded = 0;
              if (TSBwhite.Checked)
              {
                thePoints[boardX, boardY].color = 1;
                colorAdded = 1;
                statusMess = "White ";
              }
              else
              {
                thePoints[boardX, boardY].color = 2;
                colorAdded = 2;
                statusMess = "Black ";
              }
              if (!ProcessMove(boardX, boardY, colorAdded)) return;
              statusMess += "played at " + toolsOptions.topLabels[boardX] + " " + toolsOptions.leftLabels[boardY];
              if (TSBblackWhite.Checked)
              {
                TSBblack.Checked = !TSBblack.Checked;
                TSBwhite.Checked = !TSBwhite.Checked;
                if (TSBblack.Checked) { panelMain.Cursor = blackCursor; }
                else { panelMain.Cursor = whiteCursor; }
              }
            }
            else
            {
              // removing a stone by clicking on it
              if (thePoints[boardX, boardY].color == 1) { statusMess = "White"; } else { statusMess = "Black"; }
              statusMess += " stone removed from " + toolsOptions.topLabels[boardX] + " " + toolsOptions.leftLabels[boardY];
              thePoints[boardX, boardY].color = 0;
              thePoints[boardX, boardY].moveAdded = 0;
            }
            if (TSBblack.Checked) { statusMess += ". Black to play"; } else { statusMess += ". White to play"; }
            EndMove(boardX, boardY, statusMess);
          }
        }
        return;
      }
      mouseDragging = false;
    }
    private bool ProcessMove(int boardX, int boardY, byte colorAdded)
    {
      int captures = CountCaptures(boardX, boardY);
      if (captures == 0)
      {
        // check for suicide
        if (CountLiberties(boardX, boardY) == 0)
        {
          // it is suicide. Not allowed. Rewind a bit
          thePoints[boardX, boardY].color = 0;
          UnSaveState("Mouse up suicide");
          new MyMessageBox("Suicide not allowed", this);
          return false;
        }
      }
      if (captures == 1)
      {
        // Check Ko. Temporarily remove prisoner
        thePoints[firstPrisoner.X, firstPrisoner.Y].color = 0;
        if (CheckForKo())
        {
          thePoints[boardX, boardY].color = 0;
          thePoints[firstPrisoner.X, firstPrisoner.Y].color = (byte)(3 - colorAdded);
          UnSaveState("Mouse up Ko");
          new MyMessageBox("Ko not allowed", this);
          return false;
        }
        thePoints[firstPrisoner.X, firstPrisoner.Y].color = (byte)(3 - colorAdded);
      }
      thePoints[boardX, boardY].moveAdded = GetNextMoveNr();
      ImprisonCaptures(boardX, boardY);
      return true;
    }
    private void EndMove(int boardX, int boardY, string message)
    {
      statusM.Set(message);
      panelMain.Invalidate(PixRectFromBoardXY(boardX, boardY));
      RedCirclesRemoveOld();
      prSLider.Invalidate();
    }
    private short GetNextMoveNr()
    {
      short nextMoveNr = 0;
      for (int x = 0; x < bSide; x++)
      {
        for (int y = 0; y < bSide; y++)
        {
          if (thePoints[x, y].moveAdded > nextMoveNr)
          {
            nextMoveNr = thePoints[x, y].moveAdded;
          }
        }
      }
      return ++nextMoveNr;
    }
    private void PanelMain_MouseDown(object sender, MouseEventArgs e)
    {
      panelMain.Focus();
      if (panelMain.Cursor == Cursors.Cross) return;
      int boardX = BoardXYfromPixelXY(e.X);
      int boardY = BoardXYfromPixelXY(e.Y);
      mouseFirstDownMs = DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond;
      // if in selection rectangle, commence move
      if (boardX >= selection.TLx() && boardX <= selection.BRx() &&
        boardY >= selection.TLy() && boardY <= selection.BRy())
      {
        // SaveState("Mouse down, commence move 1");
        if (gameInProgress) { return; }
        selection.StartDrag();
        TLpasteCx = selection.TLx(); TLpasteCy = selection.TLy();
        BRpasteCx = selection.BRx(); BRpasteCy = selection.BRy();
        mouseDown = true;
        panelMain.Cursor = Cursors.Hand;
        return;
      }
      if (!NearPoint(e.X, e.Y))
      {
        mouseDragging = false;
        mouseDown = true;
        mouseDownX = e.X;
        mouseDownY = e.Y;
        return;
      }
      // we are near a point. If it is a stone, select it
      if (thePoints[boardX, boardY].color == 0)
      {
        mouseDragging = false;
        mouseDown = true;
        mouseDownX = e.X;
        mouseDownY = e.Y;
        return;
      }
      // is a stone, select it and start moving it
      // SaveState("Mouse down, commence move 2");
      if (gameInProgress) { return; }
      selection.UpdateRect(e.X, e.Y, e.X, e.Y);
      selection.StartDrag();
      TLpasteCx = boardX; TLpasteCy = boardY; BRpasteCx = boardX; BRpasteCy = boardY;
      mouseDragging = false;
      mouseDown = true;
      panelMain.Cursor = Cursors.Hand;
    }
    private void PanelMain_MyHover(object sender, EventArgs e)
    {
      // MouseHover event only called when mouse moves in from other control
      // this one works when mouse moves within the control
      if (mouseBoardX != -1)
      {
        if (thePoints[mouseBoardX, mouseBoardY].color != 0)
        {
          UpdateTSTextBox1(toolsOptions.topLabels[mouseBoardX] + " " +
            toolsOptions.leftLabels[mouseBoardY] + 
            ". Liberties " + CountLiberties(mouseBoardX, mouseBoardY) + ".");
        }
      }
    }
    // Suppress Exception messages (except the first) in debugger output 
    // just for UpdateTSTextBox1. Also disables debugging in UpdateTSTextBox1.
    [System.Diagnostics.DebuggerStepThrough]
    private void UpdateTSTextBox1 (string text)
    {
      TSTextBox1Text = text;
      try
      {
        TSTextBox1.Text = TSTextBox1Text;
        // Console.WriteLine("Normal update " + TSTextBox1Text);
      }
      catch (InvalidOperationException)
      {
        // cross-thread exception, usually produces a warning in debug output
        Invoke(new Action(() => { TSTextBox1.Text = TSTextBox1Text; }));
        // Console.WriteLine("Abnormal update " + TSTextBox1Text);
      }
      // coplilot's suggestion to avoid cross-thread exception
      // did not work on David' machine or my laptop
      // it would need to process TSTextBox1_Paint
      //if (InvokeRequired)
      //{
      //  Console.WriteLine("InvokeRequired " + text);
      //  Invoke(new Action(() => TSTextBox1.Invalidate()));
      //}
      //else
      //{
      //  Console.WriteLine("No InvokeRequired " + text);
      //  TSTextBox1.Invalidate();
      //}
    }
    private void PanelMain_MouseMove(object sender, MouseEventArgs e)
    {
      Point thePoint = NearBoardXY(e.X, e.Y);
      if (thePoint.X != -1)
      {
        if (mouseBoardX != thePoint.X || mouseBoardY != thePoint.Y)
        {
          mouseMoveTimer.Stop();
          UpdateTSTextBox1(toolsOptions.topLabels[thePoint.X] + " " +
            toolsOptions.leftLabels[thePoint.Y]);
        }
        mouseMoveTimer.Start();
      }
      else
      {
        mouseMoveTimer.Stop();
        UpdateTSTextBox1("");
      }
      mouseBoardX = thePoint.X;
      mouseBoardY = thePoint.Y;

      if ((panelMain.Cursor == Cursors.Cross) || (panelMain.Cursor == Cursors.Hand))
      {
        int newEX = BoardXYfromPixelXY(e.X);
        int newEY = BoardXYfromPixelXY(e.Y);

        if ((newEX == TLpasteCx) && (newEY == TLpasteCy)) return;
        if (!LegalMove(newEX, newEY)) return;

        panelMain.Invalidate(PixRectFromBoardRect(TLpasteCx, TLpasteCy,
          BRpasteCx, BRpasteCy));
        BRpasteCx += newEX - TLpasteCx;
        BRpasteCy += newEY - TLpasteCy;
        TLpasteCx = newEX;
        TLpasteCy = newEY;
        panelMain.Invalidate(PixRectFromBoardRect(TLpasteCx, TLpasteCy,
          BRpasteCx, BRpasteCy));
        return;
      }
      if (!mouseDown) return;
      const int margin = 2;
      if (e.X >= mouseDownX - margin && e.X <= mouseDownX + margin &&
        e.Y >= mouseDownY - margin && e.Y <= mouseDownY + margin)
      {
        return;   // have not moved enough to start creation of selection rectangle
      }
      // we have mouseDownX, mouseDownY as one corner of selection rectangle
      // and e.X, e.Y as other corner
      // arrange them so that first pair is top left corner, second is bottom right
      int BRx = e.X; int BRy = e.Y;
      int TLx = mouseDownX; int TLy = mouseDownY;
      if (BRx < TLx) { (TLx, BRx) = (BRx, TLx); }
      if (BRy < TLy) { (TLy, BRy) = (BRy, TLy); }
      selection.UpdateRect(TLx, TLy, BRx, BRy);
      mouseDragging = true;
    }
    private bool LegalMove(int x, int y)
    {
      // single stone may only move onto self or empty point. Cannot move onto any prisoner either
      if (selection.movePoints.GetLength(0) * selection.movePoints.GetLength(1) == 1 &&
        thePoints[x, y].color != 0)
      {
        // not allowed to paste singleton on top of existing stone
        // unless it is the original stone, which must be the only stone with top bit set
        if ((thePoints[x, y].color & 0x80) != 0x80)
          return false;
      }
      return true;
    }
    private bool NearPoint(int x, int y)
    {
      int cellSide = PixelXYfromBoardXY(0);
      int nearestPx = PixelXYfromBoardXY(BoardXYfromPixelXY(x));
      int nearestPy = PixelXYfromBoardXY(BoardXYfromPixelXY(y));

      return (Math.Abs(nearestPx - x) <= cellSide / 3) && (Math.Abs(nearestPy - y) <= cellSide / 3);
    }
    private Point NearBoardXY(int x, int y)
    {
      Point result = new Point(BoardXYfromPixelXY(x), BoardXYfromPixelXY(y));
      if (!NearPoint(x, y))
      {
        result.X = -1;
      }
      return result;
    }
    public int BoardXYfromPixelXY(int pixelXY)
    {
      int squareSide = panelMain.Width;
      if (panelMain.Height < squareSide) { squareSide = panelMain.Height; }
      int cellSide = squareSide / (bSide + 1);
      int index = (pixelXY - cellSide / 2) / cellSide;   //... / 2 for rounding
      if (index < 0) { return 0; }
      if (index >= bSide) { return bSide - 1; }
      return index;
    }
    public int PixelXYfromBoardXY(int boardXY)
    {
      int squareSide = panelMain.Width;
      if (panelMain.Height < squareSide) { squareSide = panelMain.Height; }
      int cellSide = squareSide / (bSide + 1);
      return cellSide + cellSide * boardXY;
    }
    public Rectangle PixRectFromBoardXY(int boardX, int boardY)
    {
      int side = PixelXYfromBoardXY(0);
      Rectangle rc = new Rectangle(0, 0, side, side)
      {
        X = PixelXYfromBoardXY(boardX) - side / 2,
        Y = PixelXYfromBoardXY(boardY) - side / 2
      };
      return rc;
    }
    public Rectangle BoardRectFromPixRect(Rectangle rectangle)
    {
      int width = BoardXYfromPixelXY(rectangle.Width);
      int height = BoardXYfromPixelXY(rectangle.Height);
      Rectangle rc = new Rectangle(0, 0, width, height)
      {
        X = BoardXYfromPixelXY(rectangle.X),
        Y = BoardXYfromPixelXY(rectangle.Y)
      };
      return rc;
    }
    public Rectangle PixRectFromBoardRect(int TRx, int TRy, int BRx, int BRy)
    {
      // pixel rectangle is half a cell outside (TRx, TRy), (BRx, BRy)
      int side = PixelXYfromBoardXY(0);
      int width = PixelXYfromBoardXY(BRx) - PixelXYfromBoardXY(TRx) + side;
      int height = PixelXYfromBoardXY(BRy) - PixelXYfromBoardXY(TRy) + side;
      Rectangle rc = new Rectangle(0, 0, width, height)
      {
        X = PixelXYfromBoardXY(TRx) - side / 2,
        Y = PixelXYfromBoardXY(TRy) - side / 2
      };
      return rc;
    }
    private float GetFontSizeForHeight(Graphics graphics, string fontName, float desiredHeight)
    {
      float fontSize = 1.0f;
      Font font = new Font(fontName, fontSize);
      SizeF size = graphics.MeasureString("A", font);

      // Increase font size until the height of 'A' is close to the desired height
      while (size.Height < desiredHeight)
      {
        fontSize += 0.5f;
        font = new Font(fontName, fontSize);
        size = graphics.MeasureString("A", font);
      }

      return fontSize;
    }

    private void PanelMain_Paint(object sender, PaintEventArgs e)
    {
      Stopwatch stopWatch = new Stopwatch();
      stopWatch.Start();
      // panelMain must be big enough for 18 + 2 squares (assuming bSide = 19)
      myPen.Color = Color.Black;
      int cellSide = PixelXYfromBoardXY(0);
      int squareSide = cellSide * (bSide + 1);
      int dotRadius = cellSide / 8;
      int stoneRadius = (int)(cellSide / 2.2);
      int RandomSeed = (DateTime.Now).Millisecond;
      Rectangle drawStones = BoardRectFromPixRect(e.ClipRectangle);

      float fontSize = GetFontSizeForHeight(e.Graphics, "Arial", cellSide * 0.4f);
      Font myFont = new Font("Arial", fontSize);
      Font fontChinese = new Font("Arial", fontSize * 0.8f);
      // draw numbers in top / bottom, left/right margin
      DrawReferenceNumbers();

      // grid lines
      for (int lineX = cellSide; lineX <= (squareSide - cellSide); lineX += cellSide)
      {
        if (lineX >= e.ClipRectangle.Left && lineX <= e.ClipRectangle.Right)
        {
          e.Graphics.DrawLine(myPen, lineX, cellSide, lineX, cellSide * bSide);
        }
      }
      for (int lineY = cellSide; lineY <= (squareSide - cellSide); lineY += cellSide)
      {
        if (lineY >= e.ClipRectangle.Top && lineY <= e.ClipRectangle.Bottom)
        {
          e.Graphics.DrawLine(myPen, cellSide, lineY, cellSide * bSide, lineY);
        }
      }
      // draw dots on board 
      DrawDot(3, 3); DrawDot(9, 3); DrawDot(15, 3);
      DrawDot(3, 9); DrawDot(9, 9); DrawDot(15, 9);
      DrawDot(3, 15); DrawDot(9, 15); DrawDot(15, 15);

      // draw stones. 
      for (int dsX = drawStones.X; dsX <= drawStones.X + drawStones.Width; dsX++)
      {
        for (int dsY = drawStones.Y; dsY <= drawStones.Y + drawStones.Height; dsY++)
        {
          if (dsX >= 0 && dsX < bSide && dsY >= 0 && dsY < bSide) 
          {
            DrawStone(thePoints, dsX, dsY, 0, 0);
            DrawScore(dsX, dsY);
            // highlight latest move
            if (undos == 0) { continue; }
            if (undos == 1 && thePoints[dsX, dsY].color > 0) { DrawRedCircle(dsX, dsY); }
            else
            {
              if (thePoints[dsX, dsY].color != undoObjects[undos - 1].urPoints[dsX, dsY].color)
              {
                DrawRedCircle(dsX, dsY);
              }
            }
          }
        }
      }

      // draw stones being pasted
      if (sender.GetType() == typeof(System.Windows.Forms.Panel))
      {
        // draw rectangles if not clipboard
        selection.DrawSelRectagle(e);
        // and paste rectangle
        if ((panelMain.Cursor == Cursors.Cross) || (panelMain.Cursor == Cursors.Hand))
        {
          int halfCell = PixelXYfromBoardXY(0) / 2;
          myPen.Color = Color.Green;
          myPen.DashStyle = System.Drawing.Drawing2D.DashStyle.Dash;
          e.Graphics.DrawRectangle(myPen, PixelXYfromBoardXY(TLpasteCx) - halfCell,
            PixelXYfromBoardXY(TLpasteCy) - halfCell,
            PixelXYfromBoardXY(BRpasteCx) - PixelXYfromBoardXY(TLpasteCx) + 2 * halfCell,
            PixelXYfromBoardXY(BRpasteCy) - PixelXYfromBoardXY(TLpasteCy) + 2 * halfCell);
          myPen.DashStyle = System.Drawing.Drawing2D.DashStyle.Solid;
          for (int x = TLpasteCx; x <= BRpasteCx; x++)
          {
            for (int y = TLpasteCy; y <= BRpasteCy; y++)
            {
              DrawStone(selection.movePoints, x - TLpasteCx, y - TLpasteCy, TLpasteCx, TLpasteCy);
            }
          }
        }

      }
      stopWatch.Stop();
      TimeSpan ts = stopWatch.Elapsed;
      int lastPaintTimeMs = ts.Seconds * 1000 + ts.Milliseconds;
      //Console.WriteLine("Paint " + lastPaintTimeMs + " ms. Clip = " + e.ClipRectangle);
      return;

      //////////////////////////////////////////
      // Functions for drawing bits and pieces
      //////////////////////////////////////////
      void DrawDot(int x, int y)
      {
        // x,y = coordinates in thePoints array
        // convert y,y to pixels, draw dot if overlaps clip rectangle
        int xPix = cellSide + x * cellSide;
        int yPix = cellSide + y * cellSide;
        Rectangle dotRect = new Rectangle(xPix - dotRadius, yPix - dotRadius,
          dotRadius * 2, dotRadius * 2);
        if (e.ClipRectangle.IntersectsWith(dotRect))
        {
          e.Graphics.FillEllipse(brushBlack, dotRect);
        }
      }
      void DrawRedCircle(int x, int y)
      {
        int xPix = cellSide + x * cellSide;
        int yPix = cellSide + y * cellSide;
        myPen.Color = Color.Red;
        myPen.Width = 3;
        Rectangle stoneRect = new Rectangle(xPix - stoneRadius, yPix - stoneRadius,
         stoneRadius * 2, stoneRadius * 2);
        e.Graphics.DrawEllipse(myPen, stoneRect);
        myPen.Width = 1;
      }
      void DrawScore(int x, int y)
      {
        // draw from results of scoring
        if (!ScGui.haveScore || toolsOptions.ShowNone.Checked) return;
        if (x < 0 || x >= bSide || y < 0 || y >= bSide) { return; }
        int xPix = cellSide + (x) * cellSide;
        int yPix = cellSide + (y) * cellSide;
        Rectangle stoneRect = new Rectangle(xPix - stoneRadius, yPix - stoneRadius,
          stoneRadius * 2, stoneRadius * 2);
        if (!e.ClipRectangle.IntersectsWith(stoneRect))
        {
          return;
        }
        if (toolsOptions.ShowRemovals.Checked && ScGui.Removals[x,y] != Color.Empty)
        {
          DrawScore2(x, y, brushRed);
        }
        if (toolsOptions.ShowTerritory.Checked && ScGui.Territories[x, y] != Color.Empty)
        {
          if (ScGui.Territories[x, y] == Color.Black)
            DrawScore2(x, y, brushBlack);
          else
            DrawScore2(x, y, brushWhite);
        }
        if (toolsOptions.ShowConnections.Checked && ScGui.Connections[x, y] != Color.Empty)
        {
          if (ScGui.Connections[x, y] == Color.Black)
            DrawScore2(x, y, brushLightBlack);
          else
            DrawScore2(x, y, brushDarkWhite);
        }
      }
      void DrawScore2(int x, int y, Brush brush)
      {
        // x,y = coordinates in thePoints array
        // convert y,y to pixels, draw dot if overlaps clip rectangle
        int radius = dotRadius * 2;
        int xPix = cellSide + x * cellSide;
        int yPix = cellSide + y * cellSide;
        Rectangle rect = new Rectangle(xPix - radius, yPix - radius,
          radius * 2, radius * 2);
        if (e.ClipRectangle.IntersectsWith(rect))
        {
          DrawStar(xPix, yPix, brush);
        }
      }
      void DrawStar (int xP, int yP, Brush brush)
      {
        // xP,yP = centre of star in pixels
        int starPoints = 10;        // double number of points on star
        int starRadius1 = dotRadius;
        int starRadius2 = dotRadius * 2;
        Point[] star = new Point[starPoints];
        double angle = (new Random(RandomSeed++)).NextDouble();
        for (int i = 0; i < starPoints; i++)
        {
          double r = (i % 2 == 0) ? starRadius1 : starRadius2;
          star[i].X = (int)(xP + r * Math.Cos(angle));
          star[i].Y = (int)(yP + r * Math.Sin(angle));
          angle += 2 * Math.PI / starPoints;
        }
        e.Graphics.FillPolygon(brush, star);
      }

      void DrawStone(AStone[,] sourceStones, int x, int y, int xBase, int yBase)
      {
        // x,y = coordinates in sourceStones array
        // xBase, yBase = offset of sourceStones in board
        if (x < 0 || x >= bSide || y < 0 || y >= bSide) { return; }
        int xPix = cellSide + (x + xBase) * cellSide;
        int yPix = cellSide + (y + yBase) * cellSide;
        Rectangle stoneRect = new Rectangle(xPix - stoneRadius, yPix - stoneRadius,
          stoneRadius * 2, stoneRadius * 2);
        if (!e.ClipRectangle.IntersectsWith(stoneRect))
        {
          return;
        }
        switch (sourceStones[x, y].color)
        {
          case 1:
            e.Graphics.FillEllipse(brushWhite, stoneRect);
            break;
          case 2:
            e.Graphics.FillEllipse(brushBlack, stoneRect);
            break;
          case 129:
            e.Graphics.FillEllipse(brushDarkWhite, stoneRect);
            break;
          case 130:
            e.Graphics.FillEllipse(brushLightBlack, stoneRect);
            break;
        }
        if (sourceStones[x, y].moveAdded == 0 || !toolsOptions.showSequence) { return; }
        string s = sourceStones[x, y].moveAdded.ToString();
        SizeF size = e.Graphics.MeasureString(s, myFont);
        if (sourceStones[x, y].color == 1)
        {
          e.Graphics.DrawString(s, myFont, brushBlack, xPix - size.Width / 2, yPix - size.Height / 2);
        }
        if (sourceStones[x, y].color == 2)
        {
          e.Graphics.DrawString(s, myFont, brushWhite, xPix - size.Width / 2, yPix - size.Height / 2);
        }

      }

      void DrawReferenceNumbers()
      {
        Rectangle rectTop = PixRectFromBoardRect(0, 0, bSide + 1, 1);
        Rectangle rectBottom = PixRectFromBoardRect(0, bSide, bSide + 1, bSide + 1);
        Rectangle rectLeft = PixRectFromBoardRect(0, 0, 1, bSide + 1);
        Rectangle rectRight = PixRectFromBoardRect(bSide, 0, bSide + 1, bSide + 1);
        if (!e.ClipRectangle.IntersectsWith(rectTop) && !e.ClipRectangle.IntersectsWith(rectBottom) &&
          !e.ClipRectangle.IntersectsWith(rectLeft) && !e.ClipRectangle.IntersectsWith(rectRight)
          ) 
        { 
          return; 
        }
        // <= .002 ms to do checks above. ~20 ms do drawing below. 
        Font theFont = myFont;
        for (int i = 0; i < bSide; i++)
        {
          string s = toolsOptions.topLabels[i];
          if (toolsOptions.topScript == 3) { theFont = fontChinese; }
          SizeF size = e.Graphics.MeasureString(s, theFont);
          e.Graphics.DrawString(s, theFont, Brushes.Black, PixelXYfromBoardXY(i) - size.Width / 2,
            cellSide - stoneRadius - size.Height);
          e.Graphics.DrawString(s, theFont, Brushes.Black, PixelXYfromBoardXY(i) - size.Width / 2,
            squareSide - cellSide + stoneRadius);
        }
        for (int i = 0; i < bSide; i++)
        {
          string s = toolsOptions.leftLabels[i];
          if (toolsOptions.leftScript == 3) { theFont = fontChinese; }
          SizeF size = e.Graphics.MeasureString(s, theFont);
          e.Graphics.DrawString(s, theFont, Brushes.Black, cellSide - stoneRadius - size.Width * 0.9f,
            PixelXYfromBoardXY(i) - size.Height / 2);
          e.Graphics.DrawString(s, theFont, Brushes.Black, squareSide - cellSide + stoneRadius,
            PixelXYfromBoardXY(i) - size.Height / 2);
        }
      }
    }
    private void RedCirclesRemoveOld()
    {
      // when a stone is added or removed it is red circled to assist visibility
      // normally only the stones added / removed are redrawn
      // We also need to redraw all stones with red circles that have gone 
      // this is done here. This method must be called after additions / removals
      if (undos < 2) {  return; }
      for (int x = 0; x < bSide; x++)
      {
        for (int y = 0; y < bSide; y++)
        {
          if (undoObjects[undos - 2].urPoints[x,y].color != undoObjects[undos - 1].urPoints[x, y].color)
          {
            panelMain.Invalidate(PixRectFromBoardXY(x, y));
          }
        }
      }
    }
    private void aboutToolStripMenuItem_Click(object sender, EventArgs e)
    {
      new HelpAbout(this);
    }
    private void helpToolStripButton_Click(object sender, EventArgs e)
    {
      aboutToolStripMenuItem_Click(sender, e);
    }
    public void TSBwhite_Click(object sender, EventArgs e)
    {
      UnClickAll();
      TSBwhite.Checked = true;
      statusM.Set("White stones will be played");
      panelMain.Cursor = whiteCursor;
    }
    public void TSBblack_Click(object sender, EventArgs e)
    {
      UnClickAll();
      TSBblack.Checked = true;
      statusM.Set("Black stones will be played");
      panelMain.Cursor = blackCursor;
    }
    public void TSBblackWhite_Click(object sender, EventArgs e)
    {
      if (TSBblackWhite.Checked)
      {
        if (TSBblack.Checked)
        {
          TSBwhite.Checked = false;
          statusM.Set("Black then White stones will be played");
          panelMain.Cursor = blackCursor;
        }
        else
        {
          TSBblack.Checked = false;
          statusM.Set("White then Black stones will be played");
          panelMain.Cursor = whiteCursor;
        }
      }
      else
      {
        if (TSBblack.Checked)
        {
          statusM.Set("Black stones will be played");
          panelMain.Cursor = blackCursor;
        }
        else
        {
          statusM.Set("White stones will be played");
          panelMain.Cursor = whiteCursor;
        }
      }
    }
    public void TSBnone_Click(object sender, EventArgs e)
    {
      // the red button
      SaveState("TSBnone_Click");
      UndoRedoBuffer emptyBoard = new UndoRedoBuffer(this);
      RestoreBoard(emptyBoard);
    }
    private void UnClickAll()
    {
      TSBblackWhite.Checked = false;
      TSBwhite.Checked = false;
      TSBblack.Checked = false;
    }
    public void NotImplementedYet(string what)
    {
      if (what == "")
      {
        new MyMessageBox("Not Implemented yet", this);
      }
      else
      {
        new MyMessageBox("Not Implemented yet", what, this);
      }
    }
    private void exitToolStripMenuItem_Click(object sender, EventArgs e)
    {
      Close();
    }
    private void optionsToolStripMenuItem_Click(object sender, EventArgs e)
    {
      toolsOptions.ShowTools();
    }

    private void refreshToolStripMenuItem_Click(object sender, EventArgs e)
    {
      panelMain.Invalidate();
    }

    //////////////////////////////////////////
    /// functions / classes to do with AStone
    //////////////////////////////////////////
    public AStone[,] CreateStones(int xDim, int yDim)
    {
      AStone[,] returnVal = new AStone[xDim, yDim];
      for (int x = 0; x < xDim; x++)
      {
        for (int y = 0; y < yDim; y++)
        {
          returnVal[x, y] = new AStone();
        }
      }
      return returnVal;
    }
    public bool LooksEqualTo (AStone st1, AStone st2)
    {
      if (st1.color != st2.color) { return false; }
      if (!toolsOptions.showSequence) { return true; }
      // colors are same
      return (st1.moveAdded == st2.moveAdded);
    }
    public void StonesOnBoard (ref int whites, ref int blacks)
    {
      whites = 0; blacks = 0;
      for (int x = 0; x < bSide; x++)
      {
        for (int y = 0; y < bSide; y++)
        {
          if (thePoints[x, y].color == 1) { whites++; }
          if (thePoints[x, y].color == 2) { blacks++; }
        }
      }
    }

    private void testConnectToolStripMenuItem_Click(object sender, EventArgs e)
    {
      Connect_Test ct =  new Connect_Test();
      ct.Show();
    }

  }
  [Serializable]          // must be [Serializable] for copy / paste. 
  public class AStone
  {
    public byte color;      // 0 blank, 1 white, 2 black, top bit set = pasting
    public short moveAdded;
    public AStone()
    {
      color = 0;
      moveAdded = 0;
    }
    public bool EqualTo(AStone other)
    {
      return (color == other.color) && (moveAdded == other.moveAdded);
    }
  }

}
